default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 1
  host: localhost
  port: 5432

development:
  <<: *default
  database: cloudgroup_api_development

production:
  <<: *default
  database: cloudgroup_api_production
  username: cloudgroup_api
  password: <%= ENV["CLOUDGROUP_API_DATABASE_PASSWORD"] %>
